/**
 * Gallery Page Component
 * Project showcase and portfolio
 */
import { BaseComponent } from '../../../js/base-component.js';
import { loadDesignSystem } from '../../../js/design-system-loader.js';
import template from './GalleryPage.html?raw';

class GalleryPage extends BaseComponent {
  constructor() {
    super();
  }

  async render() {
    // Load design system CSS variables
    const designSystemStyles = await loadDesignSystem();

    this.shadowRoot.innerHTML = `
      <style>
        ${designSystemStyles}
        ${this.getComponentStyles()}
      </style>
      ${template}
    `;
  }

  getComponentStyles() {
    return `
      :host {
        display: block;
        width: 100%;
      }
      .galleryPage {
        width: 100%;
      }
      .pageHeader {
        background: var(--color-bg-dark);
        color: #fff;
        padding: var(--section-padding-mobile) var(--spacing-md);
        text-align: center;
      }
      .pageTitle {
        font-size: var(--font-size-h1-mobile);
        font-weight: 700;
        line-height: var(--line-height-tight);
        margin: 0;
        color: #fff;
      }
      @media (min-width: 768px) {
        .pageTitle {
          font-size: var(--font-size-h1-desktop);
        }
        .pageHeader {
          padding: var(--section-padding-tablet) var(--spacing-lg);
        }
      }
      @media (min-width: 1024px) {
        .pageHeader {
          padding: var(--section-padding-desktop) var(--spacing-xl);
        }
      }
      .gallerySection {
        padding: var(--section-padding-mobile) var(--spacing-md);
        max-width: var(--content-width-max);
        margin: 0 auto;
        width: 100%;
      }
      @media (min-width: 768px) {
        .gallerySection {
          padding: var(--section-padding-tablet) var(--spacing-lg);
        }
      }
      @media (min-width: 1024px) {
        .gallerySection {
          padding: var(--section-padding-desktop) var(--spacing-xl);
        }
      }
      .galleryContainer {
        /* Gallery will be generated by existing gallery.js */
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: var(--spacing-sm);
      }
    `;
  }

  init() {
    // Initialize gallery using existing gallery.js
    // Load gallery data and render
    this.loadGallery();
  }

  async loadGallery() {
    const galleryContainer = this.$q('.galleryContainer');
    if (!galleryContainer) return;

    try {
      // Load gallery data
      const response = await fetch('/data/gallery.json');
      const data = await response.json();
      
      if (!data || !data.photos || data.photos.length === 0) {
        galleryContainer.innerHTML = '<p style="text-align: center; padding: 2rem;">Brak zdjęć w galerii.</p>';
        return;
      }

      // Generate gallery HTML
      let galleryHTML = '';
      data.photos.forEach((photo, index) => {
        const imagePath = `/i/${photo.folder}/${photo.filename}`;
        const thumbPath = photo.thumbFilename ? `/i/${photo.folder}/${photo.thumbFilename}` : imagePath;
        
        galleryHTML += `
          <div class="gallery-item" style="flex: 0 0 calc(33.333% - 8px); margin: 4px;">
            <a href="${imagePath}" class="glightbox" data-glightbox="title: ${photo.title || ''}; description: ${photo.description || ''}">
              <img src="${thumbPath}" alt="${photo.title || 'Galeria zdjęć'}" loading="lazy" style="width: 100%; height: auto; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); transition: transform 0.3s ease;" />
            </a>
          </div>
        `;
      });

      galleryContainer.innerHTML = galleryHTML;

      // Initialize GLightbox
      if (window.GLightbox) {
        const lightbox = GLightbox({
          selector: '.glightbox',
          touchNavigation: true,
          loop: true,
          autoplayVideos: true
        });
      } else {
        // Load GLightbox if not available
        const script = document.createElement('script');
        script.src = 'https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js';
        script.onload = () => {
          const lightbox = GLightbox({
            selector: '.glightbox',
            touchNavigation: true,
            loop: true
          });
        };
        document.head.appendChild(script);
        
        const link = document.createElement('link');
        link.rel = 'stylesheet';
        link.href = 'https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.css';
        document.head.appendChild(link);
      }
    } catch (error) {
      console.error('Error loading gallery:', error);
      galleryContainer.innerHTML = '<p style="text-align: center; padding: 2rem; color: var(--color-text-secondary);">Wystąpił błąd podczas ładowania galerii.</p>';
    }
  }
}

customElements.define('amf-gallery-page', GalleryPage);
export default GalleryPage;

